### ISSUE TITLE
无法使用（已解决）

### ISSUE THREAD

**Issue by a308667911** [Felix3322/PotPlayer_Chatgpt_Translate#2]
key我知道，那个 name 填的是哪个name?

点那个测试 错误 不显示

我看数据 能访问到openai 接口，但是 pot 不翻译，还是原文

**Comment by a308667911** [comment]
那个 name 留空，不需要填写，只需要写 key 就行

**Comment by Felix3322** [comment]
> 那个 name 留空，不需要填写，只需要写 key 就行

亻尔讠兑白勺又寸 name填的是模型名称
