### ISSUE TITLE
能否增加一些 降低延迟的 参数？

### ISSUE THREAD

**Issue by a308667911** [Felix3322/PotPlayer_Chatgpt_Translate#3]
比如 下面 百度 翻译 插件 类似 的 一段代码

int coolTime = 100;//冷却时间，这里的单位是毫秒，1秒钟=1000毫秒，如果提示 error:54003, 那么就加大这个数字，建议一次加100

因为 使用的场景 是直播的字幕翻译，测试了一下，一但  字符 或者 token 超过20-40 ，要等个几秒 才能显示出 翻译内容 ......

**Comment by Felix3322** [comment]
> 比如 下面 百度 翻译 插件 类似 的 一段代码
> 
> 
> 
> int coolTime = 100;//冷却时间，这里的单位是毫秒，1秒钟=1000毫秒，如果提示 error:54003, 那么就加大这个数字，建议一次加100
> 
> 
> 
> 因为 使用的场景 是直播的字幕翻译，测试了一下，一但  字符 或者 token 超过20-40 ，要等个几秒 才能显示出 翻译内容 ......
> 
> 
> 
> 

知道了以后有时间搞 我最近学期末要补作业

**Comment by Felix3322** [comment]
> 比如 下面 百度 翻译 插件 类似 的 一段代码
> 
> 
> 
> int coolTime = 100;//冷却时间，这里的单位是毫秒，1秒钟=1000毫秒，如果提示 error:54003, 那么就加大这个数字，建议一次加100
> 
> 
> 
> 因为 使用的场景 是直播的字幕翻译，测试了一下，一但  字符 或者 token 超过20-40 ，要等个几秒 才能显示出 翻译内容 ......
> 
> 
> 
> 

等几秒没办法啊 gpt输出要时间的啊 这不是冷却的问题吧 我原来做的一个软件多线程用一个key都没有超过频率上限

**Comment by a308667911** [comment]
感谢 有空修改一下，可以参考一下 这个人 写的 百度 代码 ，我用的他的 反应很快，虽然是 机翻啦 ，你看看有没有什么 办法
https://github.com/fjqingyou/PotPlayer_Subtitle_Translate_Baidu

**Comment by a308667911** [comment]
> > 比如 下面 百度 翻译 插件 类似 的 一段代码
> > int coolTime = 100;//冷却时间，这里的单位是毫秒，1秒钟=1000毫秒，如果提示 error:54003, 那么就加大这个数字，建议一次加100
> > 因为 使用的场景 是直播的字幕翻译，测试了一下，一但  字符 或者 token 超过20-40 ，要等个几秒 才能显示出 翻译内容 ......
> 
> 等几秒没办法啊 gpt输出要时间的啊 这不是冷却的问题吧 我原来做的一个软件多线程用一个key都没有超过频率上限

感谢 有空修改一下，可以参考一下 这个人 写的 百度 代码 ，我用的他的 反应很快，虽然是 机翻啦 ，你看看有没有什么 办法
https://github.com/fjqingyou/PotPlayer_Subtitle_Translate_Baidu

**Comment by a308667911** [comment]
> angle script好像支持和python一起工作 我去查查官方文档吧

唉我们这种 小白 就知道 微调一下，架设那些 太难了 ......

**Comment by a308667911** [comment]
> angle script好像支持和python一起工作 我去查查官方文档吧

我看过有人训练的本地模型 架设起来 麻烦 而且 显卡 显存 要求 很高，这就卡住好多人了

**Comment by Felix3322** [comment]
我知道啊 搞个lama小模型

**Comment by Felix3322** [comment]
但确实 普通人显卡基本都是核心顯卡一类的
