### ISSUE TITLE
参考你的模型，写了个ollama本地的模型，感谢

### ISSUE THREAD

**Issue by yxyxyz6** [Felix3322/PotPlayer_Chatgpt_Translate#4]
https://github.com/yxyxyz6/PotPlayer_ollama_Translate/tree/main

**Comment by Felix3322** [comment]
挺好的 帮我点个star吧

**Comment by Felix3322** [comment]
兄弟 你项目加个MIT协议，你用我代码要附带[原协议](https://github.com/Felix3322/PotPlayer_Chatgpt_Translate/blob/master/LICENCE)的哦

**Comment by yxyxyz6** [comment]
怎么加，没研究过

**Comment by yxyxyz6** [comment]
应该是加好了 ，你看看

**Comment by yxyxyz6** [comment]
> 挺好的 帮我点个star吧

我点过了的

**Comment by Felix3322** [comment]
嗯嗯 mua～
