### ISSUE TITLE
功能请求：支持第三方 API 代理端点

### ISSUE THREAD

**Issue by SupportSpark** [Felix3322/PotPlayer_Chatgpt_Translate#6]
### 当前问题
目前，直接修改配置文件中的官方 API 端点为第三方代理端点无法生效。这限制了用户使用 API 服务的能力。

### 功能描述
我们需要添加对第三方 API 代理端点（如 new-api 等）的支持，以允许用户灵活选择和使用非官方的 API 服务。

### 具体需求
1. 允许用户在配置中指定第三方 API 代理端点
2. 确保系统能够识别并正确使用这些自定义端点
3. 优先支持常用的第三方代理，如 new-api等
4. 保持与现有功能的兼容性

### 预期好处
1. 增加用户使用替代 API 服务的灵活性
2. 可能改善某些地区的访问速度和稳定性
3. 为用户提供更多选择，以满足特定需求（如绕过限制、负载均衡等）

### 实现建议
1. 在配置文件中添加新的选项，用于指定自定义 API 端点
2. 修改 API 请求逻辑，优先使用用户指定的自定义端点
3. 为常用的第三方代理（如 new-api）添加预设选项
4. 更新文档，说明如何使用和配置第三方 API 端点

**Comment by Felix3322** [comment]
知道了，ai别烦我，老忙了

**Comment by Felix3322** [comment]
改不了一点，前端界面就几个模板，没法方3个选项

**Comment by Felix3322** [comment]
![image](https://github.com/user-attachments/assets/69a27689-35f0-4bcb-acb2-f6f94be01769)
这不是能改的吗

**Comment by SupportSpark** [comment]
> ![图像](https://private-user-images.githubusercontent.com/115849429/395642647-69a27689-35f0-4bcb-acb2-f6f94be01769.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMTAzNjAsIm5iZiI6MTczNDExMDA2MCwicGF0aCI6Ii8xMTU4NDk0MjkvMzk1NjQyNjQ3LTY5YTI3Njg5LTM1ZjAtNGJjYi1hY2IyLWY2Zjk0YmUwMTc2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxNzE0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTFlZTY3NDNjM2Q4M2IxOTFlYjU3ZTdkNGVmMTdhMTQyMzllNDIxMGRjMDZkMDEzZWM0ZGJkZTc3ZDUzODdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.U5nTSu7sdCgLLh62nlE-zuhpJxHLcQYfHzU-HlViaug) 这不是能改变的吗

试过直接修改配置文件的端点信息，无法调用

**Comment by Felix3322** [comment]
知道了我看看

**Comment by Felix3322** [comment]
兄弟在吗，你看看是不是你的问题捏。代码真没问题

**Comment by SupportSpark** [comment]
![image](https://github.com/user-attachments/assets/8f69ad71-c4fc-414c-b1fb-854b7abb23a0)
![image](https://github.com/user-attachments/assets/f6e95287-6ec1-40ad-b1ec-6032e1984ec9)
点击测试弹窗空白
以下为了测试信息（有效的）
string api_key = "sk-FWTRfS7Bs8OFZftgt6bGocuL9CP46JgVx9PmvVMtbSlRKiGm";
string selected_model = "Qwen2.5-72B-Instruct"; // Default model
string UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)";
string apiUrl = "https://api.auusn.com/v1/chat/completions"; // Updated apiUrl definition

**Comment by Felix3322** [comment]
你这个api和openai的请求格式一样？

**Comment by Felix3322** [comment]
你们咋都是原始语言日语啊，坏孩子

**Comment by SupportSpark** [comment]
是的，相当于把很多个openai  key集合到一块轮询使用   请求格式是一样的

**Comment by Felix3322** [comment]
你用py试一下吧

**Comment by SupportSpark** [comment]
> 你们咋都是原始语言日语啊，坏孩子

(*∩_∩*)
生产力呀  哈哈

**Comment by Felix3322** [comment]
好好好，另外一个人似乎是看番
`import requests
import json

# API details from your example
api_key = "sk-FWTRfS7Bs8OFZftgt6bGocuL9CP46JgVx9PmvVMtbSlRKiGm"
selected_model = "Qwen2.5-72B-Instruct"
UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
apiUrl = "https://api.auusn.com/v1/chat/completions"

# Define the headers for the request
headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json",
    "User-Agent": UserAgent
}

# Define the payload for the request
payload = {
    "model": selected_model,
    "messages": [{"role": "user", "content": "你好"}]
}

# Make the POST request to the API
response = requests.post(apiUrl, headers=headers, json=payload)

# Check if the response is valid
if response.status_code == 200:
    # Parse and print the response JSON
    response_data = response.json()
    answer = response_data.get('choices', [{}])[0].get('message', {}).get('content', 'No answer')
    print(f"Answer: {answer}")
else:
    print(f"Request failed with status code {response.status_code}")

`
自己运行一下，有没有回复，没有就是这个api和openaiapi格式不同

**Comment by Felix3322** [comment]
md是真的烦，注释变成粗体了

**Comment by Felix3322** [comment]
这人看的东西gpt都看不下去了
https://github.com/Felix3322/PotPlayer_Chatgpt_Translate/issues/5#issuecomment-2539892322

**Comment by SupportSpark** [comment]
![image](https://github.com/user-attachments/assets/35fb6efa-92d3-4376-9b8b-04df04351f2a)

正常的


> 好吧，另外一个人似乎在看番
> 
> ```
> import requests
> import json
> api_key = "sk-FWTRfS7Bs8OFZftgt6bGocuL9CP46JgVx9PmvVMtbSlRKiGm"
> selected_model = "Qwen2.5-72B-Instruct"
> UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
> apiUrl = "https://api.auusn.com/v1/chat/completions"
> headers = {
>     "Authorization": f"Bearer {api_key}",
>     "Content-Type": "application/json",
>     "User-Agent": UserAgent
> }
> payload = {
>     "model": selected_model,
>     "messages": [{"role": "user", "content": "你好"}]
> }
> response = requests.post(apiUrl, headers=headers, json=payload)
> if response.status_code == 200:
>     response_data = response.json()
>     answer = response_data.get('choices', [{}])[0].get('message', {}).get('content', 'No answer')
>     print(f"Answer: {answer}")
> else:
>     print(f"Request failed with status code {response.status_code}")
> ```
> 
> 自己运行一下，有没有回复，没有就是这个api和openaiapi格式不同

**Comment by Felix3322** [comment]
哦
奇怪哦

**Comment by SupportSpark** [comment]
> 这人看的东西gpt都看不下去了 [#5（评论）](https://github.com/Felix3322/PotPlayer_Chatgpt_Translate/issues/5#issuecomment-2539892322)

熟悉的画风

**Comment by Felix3322** [comment]
```
import requests
import json
api_key = "sk-FWTRfS7Bs8OFZftgt6bGocuL9CP46JgVx9PmvVMtbSlRKiGm"
selected_model = "Qwen2.5-72B-Instruct"
UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
apiUrl = "https://api.auusn.com/v1/chat/completions"
headers = {
    "Authorization": f"Bearer {api_key}",
    "Content-Type": "application/json",
    "User-Agent": UserAgent
}
payload = {
    "model": selected_model,
    "messages": [{"role": "user", "content": "你好"}]
}
response = requests.post(apiUrl, headers=headers, json=payload)
if response.status_code == 200:
    response_data = response.json()
    answer = response_data.get('choices', [{}])[0].get('message', {}).get('content', 'No answer')
    print(f"Answer: {answer}")
else:
    print(f"Request failed with status code {response.status_code}")
```
好像是脚本的模型切换没做好，回家了再改

**Comment by SupportSpark** [comment]
上面的key有1天有效期，你可以用它进行测试。

今天是周末，看起来你似乎还在上班~

**Comment by Felix3322** [comment]
没上班，我上学呢，我初中生

**Comment by Felix3322** [comment]
所天没睡好

**Comment by Felix3322** [comment]
我的模型选择太混乱了，要好好理理

**Comment by Felix3322** [comment]
知道了，不是请求格式问题，是模型被错误的赋值成了4omini所以你用不了

**Comment by Felix3322** [comment]
丸辣，越改越不明白了。自己写的自己看不懂了

**Comment by SupportSpark** [comment]
> 丸辣，越改越看不懂了。自己写的自己看不懂了

我想我知道怎么解决了，直接把qwen重定向成gpt-4o-mini就解决了，

**Comment by Felix3322** [comment]
嗯嗯 谢谢

**Comment by Felix3322** [comment]
@SupportSpark 已解决此问题，https://github.com/deanhzed/PotPlayer_Chatgpt_Translate/commit/3ea573ced436823356d38c740d554c0d0624ed63
