### ISSUE TITLE
500K token 不够26分钟的剧正常吗

### ISSUE THREAD

**Issue by deanhzed** [Felix3322/PotPlayer_Chatgpt_Translate#8]
![图片](https://github.com/user-attachments/assets/7a98ae10-0245-46db-8b82-903e4acb0513)
或者说是别的什么的原因

**Comment by Felix3322** [comment]
正常 如果你嫌太多 可以使用无上下文的版本

**Comment by Felix3322** [comment]
上下文确实非常费token

**Comment by Felix3322** [comment]
@deanhzed 已添加[无上下文的版本](https://github.com/Felix3322/PotPlayer_Chatgpt_Translate/tree/WithoutContextHandling)
