### ISSUE TITLE
Siliconflow Model 支持

### ISSUE THREAD

**Issue by deanhzed** [Felix3322/PotPlayer_Chatgpt_Translate#9]
已知`Siliconflow`的`Model`名称如`Qwen/Qwen2.5-7B-Instruct`疑似支持不良
```
// Global Variables
string api_key = "sk-etjunamkfynugqethjxazzgzljbojlmnxdqazshgqfsehjim";
string selected_model = "Qwen/Qwen2.5-7B-Instruct"; // Default model
string UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64)";
string apiUrl = "https://api.siliconflow.cn/v1/chat/completions"; // Added apiUrl definition
```
显示可正常处理
![图片](https://github.com/user-attachments/assets/036e0f59-194a-460e-8109-3adcf5c95358)
但是测试失败
![图片](https://github.com/user-attachments/assets/d0ee54ea-15f6-4a25-be42-3a0c43582caf)

**Comment by deanhzed** [comment]
已解决
https://github.com/deanhzed/PotPlayer_Chatgpt_Translate/commit/3ea573ced436823356d38c740d554c0d0624ed63

**Comment by Felix3322** [comment]
我一开始是防止有人用大写GPT模型的 后来我自己都忘了
